module.exports = {
    NAME : "Vince Rickey",
    LANDING_SUBTITLE : "Software Engineer with 10+ years of experience in Android & Mobile Engineering. Currently @WSJ",
    ABOUT_TITLE : "About",
    ABOUT_DESCRIPTION : "Android mobile software engineer with experience in Compose, modular app architecture, design systems, mobile payments, authentication, and GraphQL at a scale of millions of users and global engineering teams.",
    ABOUT_INDUSTRY_ITEM : "10+ years of experience in Android applications and mobile engineering in industry setting",
    ABOUT_INDUSTRY_SUBITEM_SCALE : "Scalable apps and subscription products with bi-weekly release automation, monitoring, A/B feature flag experiments, analytics, and bug resolution",
    ABOUT_INDUSTRY_SUBITEM_TEST : " Maintainable and testable code bases including API design and test pyramid strategy (unit, integration, UI tests)",
    ABOUT_INDUSTRY_SUBITEM_ACCESS : "Accessible UI/UX in Android and iOS including custom design systems and read-to-me functionality",
    ABOUT_INDUSTRY_SUBITEM_PERFORMANCE : "High Performance multithreaded and memory-optimized native apps and hybrid web apps",
    ABOUT_INDUSTRY_SUBITEM_PLANNING : "Technical and project planning from an idea to execution with global parallelized teams in Agile Scrum, Sprint Zero, Kanban, and Waterfall",
    ABOUT_INDUSTRY_ITEM_KOTLIN_COMPOSE : "7+ years of experience in Kotlin and Jetpack Compose (early adopter)",
    ABOUT_INDUSTRY_ITEM_DIRECTION : "3+ years of of experience in setting direction for global team of 50+ engineers and 150+ cross-functional colleagues across Android, iOS, Web, Backend, Product, and Design",
    WSJ : "WSJ",
    OPEN_SOURCE : "Open Source",
    ANDROID_KOTLIN : "Android | Kotlin",
    ANDROID_JAVA : "Android | Java",
    WEB : "Web | JavaScript",
    IOS : "iOS",
    RESUME : "Resume",
    KEY_RESULTS_TITLE : "Key Results",
    KEY_RESULTS_SUBTITLE : "Engineering solutions at scale",
    KEY_RESULT_PLAY_ANCHOR : "#2 News App in the Google Play Store",
    KEY_RESULT_PLAY_TEXT : " with 1+ million downloads",
    TABLE_HEADER_NUMBER : "#",
    TABLE_HEADER_DOMAIN : "Domain",
    TABLE_HEADER_TECHNICAL : "Technical Achievement",
    TABLE_HEADER_IMPACT : "Impact",
    TABLE_HEADER_RESULT : "Result",
    TABLE_ITEM_SUBSCRIPTION_DOMAIN : "Subscriptions",
    TABLE_ITEM_SUBSCRIPTION_TECHNICAL : "7 subscription flows, 4 user states, & dynamic paywall",
    TABLE_ITEM_SUBSCRIPTION_IMPACT : "Revenue",
    TABLE_ITEM_SUBSCRIPTION_RESULT : "Infrastructure drives millions of dollars in revenue",
    TABLE_ITEM_ARCHITECTURE_DOMAIN : "Architecture",
    TABLE_ITEM_ARCHITECTURE_TECHNICAL : "4 modules to 53 modules",
    TABLE_ITEM_ARCHITECTURE_IMPACT : "Scale",
    TABLE_ITEM_ARCHITECTURE_RESULT : "Consolidates 4 teams: eliminate redundancy, maximize reuse",
    TABLE_ITEM_TECH_DOMAIN : "Tech Stack",
    TABLE_ITEM_TECH_TECHNICAL : "84% Java to 91% Kotlin",
    TABLE_ITEM_TECH_IMPACT : "Innovation",
    TABLE_ITEM_TECH_RESULT : "Support latest OS features",
    TABLE_ITEM_UI_DOMAIN : "UI",
    TABLE_ITEM_UI_TECHNICAL : "100% View to 100% Compose",
    TABLE_ITEM_UI_IMPACT : "Time to market, Reactive UI",
    TABLE_ITEM_UI_RESULT : "Faster to develop, test, release, and maintain complex UI states",
    TABLE_ITEM_RELEASE_DOMAIN : "Releases",
    TABLE_ITEM_RELEASE_TECHNICAL : "~11 min build time, automated app store releases",
    TABLE_ITEM_RELEASE_IMPACT : "Agility",
    TABLE_ITEM_RELEASE_RESULT : "No code freezes: merge or release any time",
    TABLE_ITEM_TESTING_DOMAIN : "Testing",
    TABLE_ITEM_TESTING_TECHNICAL : "91 to 693 unit tests (+661%)",
    TABLE_ITEM_TESTING_IMPACT : "Resiliency",
    TABLE_ITEM_TESTING_RESULT : "Automate QA",
    ROLES_TITLE : "Roles",
    ROLES_SUBTITLE : "Project Snapshots",
    ROLES_STAFF : "Staff Software Engineer (Android)",
    ROLES_STAFF_DATE : "Jan 2023 - Present",
    ROLES_STAFF_APP_PLATFORM : "Replaced legacy apps with Compose & GraphQL white-label app platform shared by four Dow Jones apps: Wall Street Journal, Barrons, FN, MarketWatch. #1 contributor with 100,000+ lines.",
    ROLES_STAFF_TEAM : "Engineering lead for 50 Android Engineers and global 150-person department.",
    ROLES_STAFF_WEBSHOP : "Replaced native app subscription flow with hybrid WebShop that included dynamic offers, flexible paywalls, web-based deployment of iOS & Android mobile app subscription experiences.",
    ROLES_LEAD : "Lead Software Engineer (Android)",
    ROLES_LEAD_DATE : "Feb 2021 - Jan 2023",
    ROLES_LEAD_MULTIPLATFORM : "Multiplatform: Flutter proof of concept, Kotlin multiplatform discovery.",
    ROLES_SENIOR : "Senior Software Engineer (Android)",
    ROLES_SENIOR_DATE : "Jan 2019 - Feb 2021",
    ROLES_SENIOR_EXPERIMENTAL : "Experimental R&D: Compose & SwiftUI “server-driven UI” for UI changes without app releases.",
    ROLES_SENIOR_LOGIN_SUB : "Login, Registration, and In-App Subscriptions: shared library for OAuth and Google Billing.",
    ROLES_SOFTWARE : "Software Engineer (Android)",
    ROLES_SOFTWARE_DATE : "Nov 2016 - Jan 2019",
    ROLES_SOFTWARE_REDESIGN : "Redesign & Editorial Tools: newsfeed and card UI layout options curated by internal mac app.",
    REDESIGN_TITLE : "Redesign",
    REDESIGN_SUBTITLE: "Design System and Editorial Tools",
    REDESIGN_SUMMARY : "In 2017 and 2022, I worked with the Design team on a complete redesign of the app where we implemented new themes, cards, articles, fonts, and navigation. Each redesign worked seamlessly with features in our internal editorial tools - Mac and Web apps - that allow editors to configure both the types of cards in the news feed and the visibility, color, and other attributes to fit the news. For example, an editor can curate a specific story in the news feed by changing its card type from a Thumbnail Card to a Portrait Card, or changing its Flashline to a “breaking red” color, then the apps will dynamically update their UI without an app release. As a result, there are thousands of possible card variants and a rich user experience created from a handful of static card types and components in our Design System. In parallel, we integrated Design Tokens across Web, iOS, Android, and Figma so that there is a single source of truth for our brand color palette, typography, and spacing.",
    PURCHASING_TITLE : " Login & Subscriptions",
    PURCHASING_SUBTITLE: "Auth0 and Google Play Billing",
    PURCHASING_SUMMARY : "There are many ways to subscribe to WSJ - through Google Play, the Apple App Store, web, phone, etc. - which leads to a complex login and entitlement system. In 2018/2019, I was the Mobile lead on an Identity project for mobile app store subscription purchases, registration, and login. We achieved our goal of unifying access to premium content across Android, iOS, and Web regardless of where the customer made their first purchase. The technical details included setting up Google Play Billing in-app purchases and receipt verification as well as a custom implementation of an Auth0/OAuth login system driven by idTokens. In 2024, this was refactored to Kotlin. We implemented 7 subscription flows to drive 4 user states and a dynamic paywall with 100% unit test coverage. In 2026, we replaced a native app subscription flow with hybrid WebShop that included dynamic offers, flexible paywalls, web-based deployment of iOS & Android mobile app subscription experiences. The Engineering behind it was complex: it is built using webkit and HTML5 message channels for two-way app<>web communication.",
    ARCH_TITLE : "Architecture Discovery",
    ARCH_SUBTITLE: "MVP, MVVM, MVI to Jetpack Compose Platform",
    ARCH_SUMMARY : "The WSJ Android app is over 10 years old which meant that it was time to re-platform to take advantage of the latest technologies in Mobile. In 2022, we started an architecture discovery process to reevaluate our data and UI flow from the ground up. We brought the architecture from a single app module written in Java with an XML content download system to a white-label, multi-module, GraphQL, fully Jetpack Compose mobile app platform with over 50 modules. It is used not only for the WSJ app, but as a white-label platform for other brands in the Dow Jones such as Market Watch, Barrons, and FN London.",
    UI_TITLE : "Experimental R&D",
    UI_SUBTITLE: "Jetpack Compose and Swift UI",
    UI_SUMMARY : "In 2019 the Mobile team started a R&D effort to determine if it was possible to create Server-Driven UI (with native views) and completely remove app store releases from our process. We developed a working cutting edge feature: a Swift UI and Jetpack Compose Component Library driven by a JSON Declarative UI Model. While we decided against adopting this in favor of a Jetpack Compose platform with a shared component library for feature teams, we have embraced being early adopters of Swift UI and Jetpack Compose. Today, a Compose component library of 85+ reusable cards and components drive 15 different Screens owned by feature teams.",
    GRAPH_TITLE : "Graph QL",
    GRAPH_SUBTITLE: "Shared Data Layer",
    GRAPH_SUMMARY : "In 2020, the App & Web Engineering teams voted to retire our legacy backend content delivery systems and move to a shared content API with GraphQL. For Mobile, this allowed us to pass on the performance benefits (and cost savings) of a much smaller download size to our users. I was a Mobile representative for a company-wide move to GraphQL and suggested Apollo Federation as the best fit for our use cases across many Engineering teams with different requirements for their schema.",
    LFWK_NAME : "Leap for WaniKani",
    LFWK_SUMMARY : "Leap for WaniKani is a hybrid Android-WebView client app for WaniKani, a spaced repetition system used to learn Japanese characters. It’s written in Kotlin and uses MVVM, Coroutines, and LiveData. (2019 Profolio Project)",
    COMPOSE_TITLE : "Jetpack Compose Cards",
    COMPOSE_SUMMARY : "A Jetpack Compose card system with JSON-driven card layouts and text styles. (2020 Portfolio Project)",
    ADAPTER_TITLE : "Adapter Delegate Cards",
    ADAPTER_SUMMARY : "A composition-over-inheritance RecyclerView which uses Components and model-driven styles. It's built with Hannes Dorfmann's library of the same name. (2019 Portfolio Project)",
    TWITTER_TITLE : "Twitter Username RxJava",
    TWITTER_SUMMARY : "A sample application that checks if a username is available on Twitter. It's written in Java and uses MVVM with RxJava. (2019 Code Sample)",
    RESUME_TITLE : "React-Bootstrap Resume Website",
    RESUME_SUMMARY : "This website was built using react-bootstrap. (2020 Portfolio Project)",
    MET_TITLE : "The Met Impressionist Showcase",
    MET_SUMMARY : "Multi-module Jetpack Compose app showcasing The Met's impressionist collection. My most recent architecture sample. (2022 Portfolio Project)",
    PLAYBOOK_TITLE : "Playbook",
    PLAYBOOK_SUBTITLE : "From idea to release",
    PLAYBOOK_LEAD : "The Product, Design, and Engineering lifespan is relatively short in Technology, but the art of the process and craft continues.",
    PLAYBOOK_CAPTION_UI : "UI / UX",
    PLAYBOOK_CAPTION_API : "API / Whiteboarding",
    PLAYBOOK_CAPTION_ANALYTICS : "Analytics",
    PLAYBOOK_CAPTION_GANTT : "GANTT",
    PLAYBOOK_DISCOVERY : "Discovery",
    PLAYBOOK_DISCOVERY_SUBTITLE : "Create documentation for MVP to parallelize teams, automate tests, and measure success",
    PLAYBOOK_DISCOVERY_GOAL : "The Goal",
    PLAYBOOK_DISCOVERY_GOAL_LEAD : "The goal of discovery is to create the Product, Design, and Engineering documentation required to drive large teams in parallel with the ability to automate tests for each task.",
    PLAYBOOK_DISCOVERY_SUMMARY : "Sometimes exactly who, what, and how can be lost in abstract business processes. Whether Agile Scrum, Kanban, Waterfall, Sprint Zero; a small group of leads or larger team; this basic discovery playbook results in the required artifacts.",
    PLAYBOOK_DISCOVERY_PROCESS : "The Collaboration Process",
    PLAYBOOK_DISCOVERY_KICKOFF : "Kickoff | Product-driven goal",
    PLAYBOOK_DISCOVERY_BREAKOUT : "Breakout Sessions | Whiteboarding, UI/UX iterations, Identify analytics to measure success",
    PLAYBOOK_DISCOVERY_REGROUP : "Regroup | Full team realignment",
    PLAYBOOK_DISCOVERY_REPEAT : "Repeat | Until V1 minimum viable product is discovered",
    PLAYBOOK_DISCOVERY_INTAKE : "Intake | Create GANTT chart for public timeline and linked order of operations by teams",
    PLAYBOOK_DISCOVERY_CREATE : "Create | Ready for dev. Bring to life.",
    PLAYBOOK_DISCOVERY_ITERATE : "Iterate | Intake fast-follow minor or patch updates or create a second Kickoff for the future",
    PLAYBOOK_DISCOVERY_OUTCOME : "The Outcome",
    PLAYBOOK_DISCOVERY_PRODUCT : "Product",
    PLAYBOOK_DISCOVERY_PRODUCT_GOAL : "Goal statement",
    PLAYBOOK_DISCOVERY_PRODUCT_EXPERIMENT : "Experimentation: feature flags, A/B tests, or decision to make first-class feature",
    PLAYBOOK_DISCOVERY_PRODUCT_ANALYTICS : "Analytics events: used to measure success",
    PLAYBOOK_DISCOVERY_PRODUCT_WHY : "Why do this? ✅ Clear goal and success metrics of MVP in a true 'ready for dev' state in GANTT Chart. ❌ Avoids Slack whirlwind after handoff, missed target launches, unable to measure outcomes.",
    PLAYBOOK_DISCOVERY_DESIGN : "Design",
    PLAYBOOK_DISCOVERY_DESIGN_UI : "UI: Screen mockups built on design system theme",
    PLAYBOOK_DISCOVERY_DESIGN_UX : "UX: User flow for loading, success, and error paths",
    PLAYBOOK_DISCOVERY_DESIGN_WHY : "Why do this? ✅ Explicit rather than implied UI & UX for engineering team to build. ❌ Avoids time consuming feedback about fonts, colors, and sizing; incorrect user flow.",
    PLAYBOOK_DISCOVERY_ENGINEERING : "Engineering IC",
    PLAYBOOK_DISCOVERY_ENGINEERING_API : "API Documentation: expected request and response format used by apps and automated tests",
    PLAYBOOK_DISCOVERY_ENGINEERING_DIAGRAM : "Sequence Diagram: the order of API calls in the systems architecture to achieve the UX",
    PLAYBOOK_DISCOVERY_ENGINEERING_SUGGESTED : "Suggested Tickets: epics, feature tasks, subtasks for parallelization",
    PLAYBOOK_DISCOVERY_ENGINEERING_TWO_PAGER : "Technical Two Pagers (optional): tech specs for each platform (iOS, Android, Web, Backend) with documentation links, code snippets, and tradeoff analysis for peer review before coding even starts",
    PLAYBOOK_DISCOVERY_ENGINEERING_WHY : "Why do this? ✅ Enables human QA and automated tests for each task rather than once at end of project. Parallelizes client and backend development. ❌ Avoids PR rejections because someone ‘did it the wrong way’, untested and undocumented projects still maintained years later.",
    PLAYBOOK_DISCOVERY_MANAGER : "Program / Engineering Manager",
    PLAYBOOK_DISCOVERY_GANTT : "GANTT Chart: public timeline and linked order of operations by teams",
    PLAYBOOK_DISCOVERY_TICKET : "Ticket Description and Acceptance Criteria: lightweight description of goal, link to documentation, and acceptance criteria in gherkin scenario/given/when/then format",
    PLAYBOOK_DISCOVERY_MANAGER_WHY : "Why do this? ✅ Avoids classic project pitfalls. ❌ Slack whirlwind, blank tickets, testing a quarter of work days before target release, missed target launches for what could have been iterative.",
    PLAYBOOK_MULTIMODULE : "Multimodule App Architecture",
    PLAYBOOK_MULTIMODULE_SUBTITLE : "App, Feature, Infra, & Foundation",
    PLAYBOOK_MULTIMODULE_SUMMARY : "For teams developing a single-product-flavor or white-label app, a multi-module monorepo project separated into App, Feature, Infra, and Foundation modules has several benefits:",
    PLAYBOOK_MULTIMODULE_SEPARATE : "Separation of Concerns: the app, feature screens, UI components, API clients, and data models keeps dependencies clear",
    PLAYBOOK_MULTIMODULE_REUSE : "Reuse: multiple teams can contribute to common infra and foundation building data models, UI components, and services",
    PLAYBOOK_MULTIMODULE_TEST : "Automated tests: easier to write when project structure enforces single responsibility and dependency injection",
    PLAYBOOK_MULTIMODULE_SWAP : "Swap Out Implementation: i.e. change your analytics provider from Firebase to Adobe without changes to consuming infra or features reporting analytics",
    PLAYBOOK_MULTIMODULE_BUILD_TIMES : "Build Times: each module can be cached in improve build times",
    PLAYBOOK_MULTIMODULE_DISTRIBUTION : "Distribution: eliminates the need to publish, version, and release internal libraries",
    PLAYBOOK_CI : "Continuous Delivery",
    PLAYBOOK_CI_SUBTITLE : "Parallelize Engineering & QA in DEV, INT, PROD",
    PLAYBOOK_THREE_ENV_TEST : "Test Environments",
    PLAYBOOK_THREE_ENV_SUMMARY : "When the app, backend, and web teams must work together to deliver features in parallel; a three-environment setup enables Engineering & QA to develop features and bug fixes in parallel.",
    PLAYBOOK_THREE_ENV_DEV_INT : "Separating an unstable DEV environment from a stable INT environment for internal users",
    PLAYBOOK_THREE_ENV_PROD : "The PROD environment for public release users.",
    PLAYBOOK_THREE_ENV_ROLE: "Each environment has a respective role and test suite rules for promotion.",
    PLAYBOOK_APP_BRANCHING_STRATEGY : "App Branching Strategy",
    PLAYBOOK_APP_BRANCHING_STRATEGY_SUMMARY : "Scaled Trunk-Based Developments offers the most intuitive and easy-to-maintain approach for app development and release.",
    PLAYBOOK_APP_BRANCHING_STRATEGY_BEFORE : "Before merging a feature pull request to the main trunk branch, a build and automated test suite must pass.",
    PLAYBOOK_APP_BRANCHING_STRATEGY_ENSURES : "This ensures that the main trunk branch can be released at any time.",
    PLAYBOOK_APP_BRANCHING_STRATEGY_HOTFIX : "The Release branches are not merged back to main and only open to HotFixes, which avoids conflict resolution time sinks and related regressions.",
    PLAYBOOK_APP_TRUNK_CAPTION : "Scaled Trunk-Based Development",
    PLAYBOOK_APP_TRUNK_SOURCE : "Trunk-Based Development",
    PLAYBOOK_TEST_PYRAMID : "Test Pyramid",
    PLAYBOOK_TEST_PYRAMID_SUBTITLE : "Unit, Integration, and UI Tests",
    PLAYBOOK_TEST_PYRAMID_SUMMARY : "The test pyramid illustrates how engineers should allocate their test coverage given a time and cost tradeoff. Depending on test environment, branching strategy, and team scale; some or all can run on PRs.",
    PLAYBOOK_TEST_PYRAMID_UI : "UI | Android runtime | Verify a user flow by asserting UI hierarchy or screenshot analysis",
    PLAYBOOK_TEST_PYRAMID_INTEGRATION : "Integration (Instrumented) | Android runtime | Verify integration of real API by asserting Response matches an expected Result",
    PLAYBOOK_TEST_PYRAMID_UNIT : "Unit | Java runtime | Verify implementation of a function returns expected Result using mock or fakes",
    PLAYBOOK_TEST_PYRAMID_SOURCE : "AnyMind Tech Blog",
    LANGUAGES_TITLE : "Languages",
    LANGUAGES_COMPUTER : "Computer",
    LANGUAGES_KOTLIN : "Kotlin | 150,000 lines",
    LANGUAGES_JAVA : "Java | 75,000 lines",
    LANGUAGES_DART : "Dart | 20,000 lines",
    LANGUAGES_JAVASCRIPT : "JavaScript / HTML / CSS | 15,000 lines",
    LANGUAGES_HUMAN : "Human",
    LANGUAGES_ENGLISH : "English 🇺🇸 | Native, Cambridge CELTA ESL Teacher",
    LANGUAGES_FRENCH : "French 🇫🇷 | CEFR B2, Full Professional",
    LANGUAGES_JAPANESE : "Japanese 🇯🇵 | JLPT 4, Lower Intermediate",
    TOOLS_TITLE : "Tools",
    TOOLS : "Activity, Fragment, ViewModel, JetPack Compose, MVVM, MVI, Clean Architecture, Reactive UI, Material Design, Coroutines, Flow, LiveData, RxJava, RESTful API, Apollo GraphQL, Git, RecyclerView, SQLite database, Room, Hilt, Dagger, Dependency injection, Auth0, OAuth, Google Play Billing, Figma, Design Tokens, CI/CD, BitRise, Test Pyramid, Unit Test, Integration Test, UI, Test, JUnit, Robolectric, Mockk, Chrome Custom Tab, WebKit, Release Management, Trunk-based Development, Technical Writing, Agile Scrum, Kanban, Waterfall, Dev Ops, Firebase Crashlytics",
    URL_GITHUB : "https://github.com/vrickey123",
    URL_GITHUB_LFWK : "https://github.com/vrickey123/LeapForWaniKani",
    URL_GITHUB_RESUME : "https://github.com/vrickey123/vrickey123.github.io",
    URL_GITHUB_COMPOSE : "https://github.com/vrickey123/JetpackComposeCards",
    URL_GITHUB_ADAPTER : "https://github.com/vrickey123/AdapterDelegateCards",
    URL_GITHUB_TWITTER : "https://github.com/vrickey123/TwitterUsername",
    URL_GITHUB_MET : "https://github.com/vrickey123/the-met-impressionist-showcase",
    URL_LINKEDIN : "https://www.linkedin.com/in/vincentrickey",
    URL_RESUME : "https://docs.google.com/document/d/1x86PaKEOlREAQMPq_DzDlo9WJhVfJUARuttorATB4Bw/edit?usp=sharing",
    URL_PLAY_WSJ : "https://play.google.com/store/apps/details?id=wsj.reader_sp",
    URL_TRUNK : "https://trunkbaseddevelopment.com",
    URL_ANYMIND : "https://anymindgroup.com/news/tech-blog/15053/",
    CONTACT : "Contact",
}