module.exports = {
    NAME : "Vince Rickey",
    LANDING_SUBTITLE : "Software Engineer with 10+ years of experience in Android & Mobile Engineering. Currently @WSJ",
    ABOUT_TITLE : "About",
    ABOUT_DESCRIPTION : "Android mobile software engineer with experience in Compose, modular app architecture, UI design systems, mobile payments, authentication, and GraphQL at a scale of millions of users and global engineering teams.",
    ABOUT_INDUSTRY_ITEM : "10+ years of experience in Android applications and mobile engineering in industry setting",
    ABOUT_INDUSTRY_SUBITEM_SCALE : "Scalable technology and subscription products with bi-weekly release automation, monitoring, A/B feature flag experiments, analytics, and bug resolution",
    ABOUT_INDUSTRY_SUBITEM_TEST : " Maintainable and testable code bases including API design and test pyramid strategy (unit, integration, UI tests)",
    ABOUT_INDUSTRY_SUBITEM_ACCESS : "Accessible UI/UX in Android and iOS including custom design systems and read-to-me functionality",
    ABOUT_INDUSTRY_SUBITEM_PERFORMANCE : "High Performance multithreaded and memory-optimized native apps and hybrid web apps",
    ABOUT_INDUSTRY_SUBITEM_PLANNING : "Technical and project planning from an idea to execution with global parallelized teams in Agile Scrum, Sprint Zero, Kanban, and Waterfall",
    ABOUT_INDUSTRY_ITEM_KOTLIN_COMPOSE : "7+ years of experience in Kotlin and Jetpack Compose (early adopter)",
    ABOUT_INDUSTRY_ITEM_DIRECTION : "3+ years of of experience in setting direction for global team of 50+ engineers and 150+ cross-functional colleagues across Android, iOS, Web, Backend, Product, and Design",
    WSJ : "WSJ",
    OPEN_SOURCE : "Open Source",
    ANDROID_KOTLIN : "Android | Kotlin",
    ANDROID_JAVA : "Android | Java",
    WEB : "Web | JavaScript",
    IOS : "iOS",
    RESUME : "Resume",
    KEY_RESULTS_TITLE : "Key Results",
    KEY_RESULTS_SUBTITLE : "Engineering solutions at scale",
    KEY_RESULT_PLAY_ANCHOR : "#2 News App in the Google Play Store",
    KEY_RESULT_PLAY_TEXT : " with 1+ million downloads",
    TABLE_HEADER_NUMBER : "#",
    TABLE_HEADER_DOMAIN : "Domain",
    TABLE_HEADER_TECHNICAL : "Technical Achievement",
    TABLE_HEADER_IMPACT : "Impact",
    TABLE_HEADER_RESULT : "Result",
    TABLE_ITEM_SUBSCRIPTION_DOMAIN : "Subscriptions",
    TABLE_ITEM_SUBSCRIPTION_TECHNICAL : "7 subscription flows, 4 user states, & dynamic paywall",
    TABLE_ITEM_SUBSCRIPTION_IMPACT : "Revenue",
    TABLE_ITEM_SUBSCRIPTION_RESULT : "Infrastructure drives millions of dollars in revenue",
    TABLE_ITEM_ARCHITECTURE_DOMAIN : "Architecture",
    TABLE_ITEM_ARCHITECTURE_TECHNICAL : "4 modules to 53 modules",
    TABLE_ITEM_ARCHITECTURE_IMPACT : "Scale",
    TABLE_ITEM_ARCHITECTURE_RESULT : "Consolidates 4 teams: eliminate redundancy, maximize reuse",
    TABLE_ITEM_TECH_DOMAIN : "Tech Stack",
    TABLE_ITEM_TECH_TECHNICAL : "84% Java to 91% Kotlin",
    TABLE_ITEM_TECH_IMPACT : "Innovation",
    TABLE_ITEM_TECH_RESULT : "Support latest OS features",
    TABLE_ITEM_UI_DOMAIN : "UI",
    TABLE_ITEM_UI_TECHNICAL : "100% View to 100% Compose",
    TABLE_ITEM_UI_IMPACT : "Time to market, Reactive UI",
    TABLE_ITEM_UI_RESULT : "Faster to develop, test, release, and maintain complex UI states",
    TABLE_ITEM_RELEASE_DOMAIN : "Releases",
    TABLE_ITEM_RELEASE_TECHNICAL : "~11 min build time, automated app store releases",
    TABLE_ITEM_RELEASE_IMPACT : "Agility",
    TABLE_ITEM_RELEASE_RESULT : "No code freezes: merge or release any time",
    TABLE_ITEM_TESTING_DOMAIN : "Testing",
    TABLE_ITEM_TESTING_TECHNICAL : "91 to 693 unit tests (+661%)",
    TABLE_ITEM_TESTING_IMPACT : "Resiliency",
    TABLE_ITEM_TESTING_RESULT : "Automate QA",
    ROLES_TITLE : "Roles",
    ROLES_SUBTITLE : "Project Snapshots",
    ROLES_STAFF : "Staff Software Engineer",
    ROLES_STAFF_DATE : "Jan 2023 - Present",
    ROLES_STAFF_APP_PLATFORM : "Replaced legacy apps with Compose & GraphQL white-label app platform shared by four Dow Jones apps: Wall Street Journal, Barrons, FN, MarketWatch. #1 contributor with 100,000+ lines.",
    ROLES_STAFF_TEAM : "Engineering lead for 50 Android Engineers and global 150-person department.",
    ROLES_STAFF_WEBSHOP : "Replaced native app subscription flow with hybrid WebShop that included dynamic offers, flexible paywalls, web-based deployment of iOS & Android mobile app subscription experiences.",
    ROLES_LEAD : "Lead Software Engineer",
    ROLES_LEAD_DATE : "Feb 2021 - Jan 2023",
    ROLES_LEAD_MULTIPLATFORM : "Multiplatform: Flutter proof of concept, Kotlin multiplatform discovery.",
    ROLES_SENIOR : "Senior Software Engineer",
    ROLES_SENIOR_DATE : "Jan 2019 - Feb 2021",
    ROLES_SENIOR_EXPERIMENTAL : "Experimental R&D: Compose & SwiftUI “server-driven UI” for UI changes without app releases.",
    ROLES_SENIOR_LOGIN_SUB : "Login, Registration, and In-App Subscriptions: shared library for OAuth and Google Billing.",
    ROLES_SOFTWARE : "Software Engineer",
    ROLES_SOFTWARE_DATE : "Nov 2016 - Jan 2019",
    ROLES_SOFTWARE_REDESIGN : "Redesign & Editorial Tools: newsfeed and card UI layout options curated by internal mac app.",
    REDESIGN_TITLE : "Redesign",
    REDESIGN_SUBTITLE: "Design System and Editorial Tools",
    REDESIGN_SUMMARY : "In 2017 and 2022, I worked with the Design team on a complete redesign of the app where we implemented new themes, cards, articles, fonts, and navigation. Each redesign worked seamlessly with features in our internal editorial tools - Mac and Web apps - that allow editors to configure both the types of cards in the news feed and the visibility, color, and other attributes to fit the news. For example, an editor can curate a specific story in the news feed by changing its card type from a Thumbnail Card to a Portrait Card, or changing its Flashline to a “breaking red” color, then the apps will dynamically update their UI without an app release. As a result, there are thousands of possible card variants and a rich user experience created from a handful of static card types and components in our Design System. In parallel, we integrated Design Tokens across Web, iOS, Android, and Figma so that there is a single source of truth for our brand color palette, typography, and spacing.",
    PURCHASING_TITLE : " Login & Subscriptions",
    PURCHASING_SUBTITLE: "Auth0 and Google Play Billing",
    PURCHASING_SUMMARY : "There are many ways to subscribe to WSJ - through Google Play, the Apple App Store, web, phone, etc. - which leads to a complex login and entitlement system. In 2018/2019, I was the Mobile lead on an Identity project for mobile app store subscription purchases, registration, and login. We achieved our goal of unifying access to premium content across Android, iOS, and Web regardless of where the customer made their first purchase. The technical details included setting up Google Play Billing in-app purchases and receipt verification as well as a custom implementation of an Auth0/OAuth login system driven by idTokens. In 2024, this was refactored to Kotlin. We implemented 7 subscription flows to drive 4 user states and a dynamic paywall with 100% unit test coverage.",
    ARCH_TITLE : "Architecture Discovery",
    ARCH_SUBTITLE: "MVP, MVVM, MVI to Jetpack Compose Platform",
    ARCH_SUMMARY : "The WSJ Android app is over 10 years old which meant there was some tech debt to take care of after a few generations of teams. In 2022, we started an architecture discovery process to reevaluate our data and UI flow from the ground up. We brought the architecture from a single app module written in Java with an XML content download system to a white-label, multi-module, GraphQL, fully Jetpack Compose mobile app platform with over 50 modules. It is used not only for the WSJ app, but as a white-label platform for other brands in the Dow Jones such as Market Watch, Barrons, and FN London.",
    UI_TITLE : "Experimental R&D",
    UI_SUBTITLE: "Jetpack Compose and Swift UI",
    UI_SUMMARY : "In 2019 the Mobile team started a R&D effort to determine if it was possible to create Server-Driven UI (with native views) and completely remove app store releases from our process. We developed a working cutting edge feature: a Swift UI and Jetpack Compose Component Library driven by a JSON Declarative UI Model. While we decided against adopting this in favor of a Jetpack Compose platform with a shared component library for feature teams, we have embraced being early adopters of Swift UI and Jetpack Compose. Today, a Compose component library of 85+ reusable cards and components drive 15 different Screens owned by feature teams.",
    GRAPH_TITLE : "Graph QL",
    GRAPH_SUBTITLE: "Shared Data Layer",
    GRAPH_SUMMARY : "In 2020, the App & Web Engineering teams voted to retire our legacy backend content delivery systems and move to a shared content API with GraphQL. For Mobile, this allowed us to pass on the performance benefits (and cost savings) of a much smaller download size to our users. I was a Mobile representative for a company-wide move to GraphQL and suggested Apollo Federation as the best fit for our use cases across many Engineering teams with different requirements for their schema.",
    LFWK_NAME : "Leap for WaniKani",
    LFWK_SUMMARY : "Leap for WaniKani is a hybrid Android-WebView client app for WaniKani, a spaced repetition system used to learn Japanese characters. It’s written in Kotlin and uses MVVM, Coroutines, and LiveData. (2019 Profolio Project)",
    COMPOSE_TITLE : "Jetpack Compose Cards",
    COMPOSE_SUMMARY : "A Jetpack Compose card system with JSON-driven card layouts and text styles. (2020 Portfolio Project)",
    ADAPTER_TITLE : "Adapter Delegate Cards",
    ADAPTER_SUMMARY : "A composition-over-inheritance RecyclerView which uses Components and model-driven styles. It's built with Hannes Dorfmann's library of the same name. (2019 Portfolio Project)",
    TWITTER_TITLE : "Twitter Username RxJava",
    TWITTER_SUMMARY : "A sample application that checks if a username is available on Twitter. It's written in Java and uses MVVM with RxJava. (2019 Code Sample)",
    RESUME_TITLE : "React-Bootstrap Resume Website",
    RESUME_SUMMARY : "This website was built using react-bootstrap. (2020 Portfolio Project)",
    MET_TITLE : "The Met Impressionist Showcase",
    MET_SUMMARY : "Multi-module Jetpack Compose app showcasing The Met's impressionist collection. My best architecture sample. (2022 Portfolio Project)",
    LANGUAGES_TITLE : "Languages",
    LANGUAGES_KOTLIN : "Kotlin | 150,000 lines",
    LANGUAGES_JAVA : "Java | 75,000 lines",
    LANGUAGES_DART : "Dart | 20,000 lines",
    LANGUAGES_JAVASCRIPT : "JavaScript / HTML / CSS | 15,000 lines",
    URL_GITHUB : "https://github.com/vrickey123",
    URL_GITHUB_LFWK : "https://github.com/vrickey123/LeapForWaniKani",
    URL_GITHUB_RESUME : "https://github.com/vrickey123/vrickey123.github.io",
    URL_GITHUB_COMPOSE : "https://github.com/vrickey123/JetpackComposeCards",
    URL_GITHUB_ADAPTER : "https://github.com/vrickey123/AdapterDelegateCards",
    URL_GITHUB_TWITTER : "https://github.com/vrickey123/TwitterUsername",
    URL_GITHUB_MET : "https://github.com/vrickey123/the-met-impressionist-showcase",
    URL_LINKEDIN : "https://www.linkedin.com/in/vincentrickey",
    URL_RESUME : "https://docs.google.com/document/d/1x86PaKEOlREAQMPq_DzDlo9WJhVfJUARuttorATB4Bw/edit?usp=sharing",
    URL_PLAY_WSJ : "https://play.google.com/store/apps/details?id=wsj.reader_sp",
    CONTACT : "Contact",
}