module.exports = {
    NAME : "Vince Rickey",
    ABOUT : "Software Engineer with five years of experience in Android. Learning Web and iOS. Currently @WSJ",
    WSJ : "WSJ",
    OPEN_SOURCE : "Open Source",
    ANDROID : "Android",
    WEB : "Web",
    IOS : "iOS",
    RESUME : "Resume",
    REDESIGN_TITLE : "Redesign",
    REDESIGN_SUBTITLE: "Design System and Editorial Tools",
    REDESIGN_SUMMARY : "In 2016/2017, I worked with the Design team on a complete redesign of the app where we implemented new cards, articles, fonts, colors, and bottom navigation. This redesign was connected to internal editorial tools that allow editors to curate the types of cards in the feed and configure the visibility, color, and other attributes of each view that makes up a card. As a result, there are thousands of possible card variants from a handful of card types. Today we are integrating Design Tokens and a new Component Design System across Web, iOS, and Android. With Web and Design, I implemented Amazon's Style Dictionary to manage our Design Tokens (the color, font, spacing, and typography values). Now we have a single source of truth that defines WSJ Jet #222222 that's used by Web, iOS, and Android.",
    PURCHASING_TITLE : "Purchasing and Login",
    PURCHASING_SUBTITLE: "Auth0 and Google Play Billing",
    PURCHASING_SUMMARY : "There are many ways to subscribe to WSJ - through Google Play, the Apple App Store, web, phone, etc. - which leads to a very complex login and entitlement system. In 2018/2019, I was the Mobile lead on a Single Sign On project that tied subscriptions through the Google Play and Amazon App Stores to our other entry points; the goal being able to purchase and sign on from any device on any platform with your subscription. The technical details included setting up purchasing and receipt verification for all both Android stores as well as an Auth0-backed login and entitlement system.",
    ARCH_TITLE : "Architecture Discovery",
    ARCH_SUBTITLE: "MVP, MVVM, MVI",
    ARCH_SUMMARY : "The WSJ Android app is nearly 10 years old and that naturally means there is some tech debt to take care of after a few generations of teams. In 2019/2020, we started an architecture discovery process to reevaluate our data and UI flow from the ground up. The team voted on MVI and our management agreed split the team in half to work on the update. I am currently on the Site Reliability Team working on the incremental refactor to MVI as well as the other initiatives described below.",
    UI_TITLE : "Server-Driven UI",
    UI_SUBTITLE: "Jetpack Compose and Swift UI",
    UI_SUMMARY : "In 2019 the Mobile team started a R&D effort to determine if it was possible to create Server-Driven UI (with native views) and completely remove app store releases from our process. We are currently working on a cutting edge feature: a Swift UI and Jetpack Compose Component Library driven by a JSON Declarative UI Model.",
    GRAPH_TITLE : "Graph QL",
    GRAPH_SUBTITLE: "Unified Data Model",
    GRAPH_SUMMARY : "In the summer of 2020, the Mobile team voted to move to GraphQL to retire our old backend systems and pass on the performance benefits of a much smaller download size to our users. I am a Mobile representitve for a company-wide move to GraphQL and suggested Apollo Federation as the best fit for our use cases across many teams.",
    LFWK_NAME : "Leap for WaniKani",
    LFWK_SUMMARY : "Leap for WaniKani is an Android client app for WaniKani, a spaced repetition system used to learn Japanese characters. It’s written in Kotlin and uses MVVM, Coroutines, and LiveData.",
    ADAPTER_TITLE : "Adapter Delegate Cards",
    ADAPTER_SUMMARY : "A proof of concept for a composition-over-inheritance RecyclerView which uses Components and model-driven styles. It's built with Hannes Dorfmann's library of the same name.",
    TWITTER_TITLE : "Twitter Username RxJava",
    TWITTER_SUMMARY : "A sample application that checks if a username is available on Twitter. It's written in Java and uses MVVM with RxJava.",
    RESUME_TITLE : "React-Bootstrap Resume Website",
    RESUME_SUMMARY : "This website was built using react-bootstrap.",
    URL_GITHUB : "https://github.com/vrickey123",
    URL_GITHUB_LFWK : "https://github.com/vrickey123/LeapForWaniKani",
    URL_PLAY_LFWK : "https://play.google.com/store/apps/details?id=com.leapsoftware.leapforwanikani&hl=en_US",
    URL_GITHUB_RESUME : "https://github.com/vrickey123/vrickey123.github.io",
    URL_GITHUB_ADAPTER : "https://github.com/vrickey123/AdapterDelegateCards",
    URL_GITHUB_TWITTER : "https://github.com/vrickey123/TwitterUsername",
    URL_LINKEDIN : "https://www.linkedin.com/in/vincentrickey",
    URL_RESUME : "https://docs.google.com/document/d/1sODXvbf0u687PYut1KaJKPpaLDFIYJjszgkopTOiOMU/edit?usp=sharing",
    CONTACT : "Contact"
}